load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "sbom",
    srcs = [
        "classify.go",
        "genconfig.go",
        "schema_validate.go",
    ],
    importpath = "github.com/bazel-contrib/supply-chain/lib/supplychain-go/internal/sbom",
    visibility = ["//:__subpackages__"],
    deps = [
        "@com_github_santhosh_tekuri_jsonschema_v5//:jsonschema",
    ],
)

go_test(
    name = "classify_test",
    srcs = ["classify_test.go"],
    deps = [
        ":sbom",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
