package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = [
        "BUILD",
        "MODULE.bazel",
    ] + [
        "//golangci_lint:srcs",
        "//gofumpt:srcs",
    ],
)
