load("@supply_chain_tools//sbom:cyclonedx.bzl", "cyclonedx")
load("@supply_chain_tools//sbom:sbom.bzl", "sbom")

package(default_visibility = ["//visibility:public"])

sbom(
    name = "lib_with_third_party_deps_sbom",
    require_root_metadata = False,
    target = "//lib:lib_with_third_party_deps",
)

cyclonedx(
    name = "lib_with_third_party_deps_cyclonedx",
    sbom = ":lib_with_third_party_deps_sbom",
)

cyclonedx(
    name = "lib_with_third_party_deps_cyclonedx_xml",
    format = "xml",
    out = "lib_with_third_party_deps_cyclonedx.xml",
    sbom = ":lib_with_third_party_deps_sbom",
)
