"""Module extensions for metadata gathering."""

_GENERATED_REPO_NAME = "supply_chain_gather_metadata_toolchains"

def _format_string_list(values):
    if not values:
        return "[]"

    return "[\n%s]" % "".join([
        "    {},\n".format(repr(value))
        for value in values
    ])

def _registered_toolchain_types_repository_impl(repository_ctx):
    repository_ctx.file("BUILD.bazel", "")
    repository_ctx.file(
        "toolchain_types.bzl",
        """# Generated by @supply_chain_tools//gather_metadata:extensions.bzl.

TOOLCHAIN_TYPES = {}
""".format(_format_string_list(repository_ctx.attr.toolchain_types)),
    )

_registered_toolchain_types_repository = repository_rule(
    implementation = _registered_toolchain_types_repository_impl,
    attrs = {
        "toolchain_types": attr.string_list(),
    },
)

def _toolchain_types_impl(module_ctx):
    toolchain_types = {}
    for module in module_ctx.modules:
        for tag in module.tags.register:
            for toolchain_type in tag.toolchain_types:
                toolchain_types[str(toolchain_type)] = None

    _registered_toolchain_types_repository(
        name = _GENERATED_REPO_NAME,
        toolchain_types = sorted(toolchain_types.keys()),
    )

toolchain_types = module_extension(
    implementation = _toolchain_types_impl,
    tag_classes = {
        "register": tag_class(
            attrs = {
                "toolchain_types": attr.label_list(mandatory = True),
            },
        ),
    },
)
