exports_files(
    [
        "cpan.bzl",
        "julia.bzl",
        "otp.bzl",
        "swift.bzl",
        "validation.bzl",
        "vscode_extension.bzl",
    ],
    visibility = [
        "//purl/private:__pkg__",
    ],
)

filegroup(
    name = "srcs",
    srcs = [
        "cpan.bzl",
        "julia.bzl",
        "otp.bzl",
        "swift.bzl",
        "validation.bzl",
        "vscode_extension.bzl",
    ],
    visibility = [
        "//purl/private:__pkg__",
    ],
)
