exports_files(
    [
        "ascii.bzl",
        "bytes.bzl",
        "strings.bzl",
    ],
    visibility = [
        "//purl/private:__pkg__",
    ],
)

filegroup(
    name = "srcs",
    srcs = [
        "ascii.bzl",
        "bytes.bzl",
        "strings.bzl",
    ],
    visibility = [
        "//purl/private:__pkg__",
    ],
)
