exports_files(
    [
        "bitbucket.bzl",
        "composer.bzl",
        "github.bzl",
        "huggingface.bzl",
        "mlflow.bzl",
        "normalization.bzl",
        "pypi.bzl",
    ],
    visibility = [
        "//purl/private:__pkg__",
    ],
)

filegroup(
    name = "srcs",
    srcs = [
        "bitbucket.bzl",
        "composer.bzl",
        "github.bzl",
        "huggingface.bzl",
        "mlflow.bzl",
        "normalization.bzl",
        "pypi.bzl",
    ],
    visibility = [
        "//purl/private:__pkg__",
    ],
)
