#!/usr/bin/env python3

"""Tool for updating the tables for PURL."""

import argparse
import json
import os
import sys

from typing import Any, List


INDENT_SIZE = 4


def _format_starlark(value: Any, indent: int = 0) -> str:
    """Format Python values as Starlark literals with stable formatting."""
    prefix = " " * indent
    next_prefix = " " * (indent + INDENT_SIZE)

    if isinstance(value, list):
        if not value:
            return "[]"

        lines = [f"{next_prefix}{_format_starlark(element, indent + INDENT_SIZE)}," for element in value]
        return "[\n" + "\n".join(lines) + f"\n{prefix}]"

    if isinstance(value, dict):
        if not value:
            return "{}"

        lines = []
        for key in sorted(value.keys()):
            formatted_value = _format_starlark(value[key], indent + INDENT_SIZE)
            lines.append(f'{next_prefix}"{key}": {formatted_value},')
        return "{\n" + "\n".join(lines) + f"\n{prefix}}}"

    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=True)

    if isinstance(value, bool):
        return "True" if value else "False"

    if value is None:
        return "None"

    raise TypeError(f"Unsupported value in spec tests: {value!r}")


def _run(args) -> int:
    lc_all = os.environ.get("LC_ALL")
    if lc_all != "en_US.UTF-8":
        print("Your environment settings will reorder the file badly.")
        print("Please rerun as:")
        print('  LC_ALL="en_US.UTF-8"', " ".join(sys.argv))
        return 0

    tests = []
    for root, dirs, files in os.walk(f"{args.spec}/tests"):
        for file in files:
            path = f"{root}/{file}"
            with open(path, "r") as f:
                data = json.load(f)

            tests.extend(data["tests"])

    with open(args.output, "w") as f:
        f.write(
            """# Generated by maintainers/tools/purl_spec_tests/main.py. DO NOT EDIT.
#
# Source: https://github.com/package-url/purl-spec

visibility([
    "//purl/private/tests/...",
])

"""
        )

        f.write("tests = ")
        f.write(_format_starlark(tests))
        f.write("\n")

    return 0


def main(argv: List[str]) -> int:
    """Main program.
    Args:
      argv: command-line arguments, such as sys.argv (including the program name
      in argv[0]).
    Returns:
      Zero on successful program termination, non-zero otherwise.
    """

    parser = argparse.ArgumentParser(description="Update spec test suite for PURL.")
    parser.add_argument(
        "--spec",
        required=True,
        help="The path to the checkout of https://github.com/package-url/purl-spec",
    )
    parser.add_argument("--output", required=True, help="The .bzl file to write to.")

    return _run(parser.parse_args(argv[1:]))


if __name__ == "__main__":
    sys.exit(main(sys.argv))
